---
version: '3.9'

services:
  order-consumer:
    network_mode: "host"
    build:
      context: .
    env_file: .env
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_DB=appointments_scheduler
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5050:5050'
